seed: 42
output_dir: /home/mithunmanivannan/projects/benchmarking_loss_functions_ecg_reconstruction/results/semiseg_ludb_training
exp_name: vit_tiny_mean_teacher_full_s42
resume: null
start_epoch: 0
device: cpu
use_amp: false

algorithm: mean_teacher
mode: scratch
pretrained_backbone: null

backbone:
  vit_tiny:
    seq_len: 2500
    patch_size: 25
    num_leads: 1
    fp16_enabled: false
decode_head:
  FCNHead:
    in_channels: 192
    in_index: 3
    channels: 128
    num_convs: 1
    concat_input: false
    dropout_ratio: 0.1
    num_classes: 4
    align_corners: false

dataset:
  ecg_dir: /home/mithunmanivannan/projects/benchmarking_loss_functions_ecg_reconstruction/external/semiseg/author_data/ludb/ecg
  label_dir: /home/mithunmanivannan/projects/benchmarking_loss_functions_ecg_reconstruction/external/semiseg/author_data/ludb/label
  index_dir: /home/mithunmanivannan/projects/benchmarking_loss_functions_ecg_reconstruction/external/semiseg/official_indices/ludb
  train_unlabeled_csv: LUDB_train_unlabeled.csv
  train_labeled_csv: LUDB_train_labeled_all.csv
  valid_csv: LUDB_valid.csv
  test_csv: LUDB_test.csv
  filename_col: waveform
  label_filename_col: label
  signal_length: 2500
  filter:
  - highpass_filter: {fs: 250, cutoff: 0.67}
  - lowpass_filter: {fs: 250, cutoff: 40}
  augmentations:
  - random_resize_crop: {target_length: 2500, scale_min: 0.5, scale_max: 2.0}
  strong_augmentations:
  - RandAugment:
      ops:
      - AmplitudeScaling: {sigma: 0.5}
      - AdaptivePowerlineNoise: {fs: 250}
      - RandomPartialWhiteNoise: {amplitude: 1, ratio: 0.5}
      - RandomPartialSineNoise: {amplitude: 1, ratio: 0.5}
      level: 10
      num_layers: 3
      prob: 0.5
  transforms:
  - standardize: {axis: [-1, -2]}
  - to_tensor: {dtype: float}

dataloader: {batch_size: 16, num_workers: 2, pin_memory: false}
train:
  epochs: 100
  accum_iter: 1
  warmup_epochs: 10
  min_lr: 0.0001
  blr: null
  lr: 0.001
  weight_decay: 0.05
  max_norm: null
  layer_decay: null
  optimizer: adamw
  optimizer_kwargs: {betas: [0.9, 0.999]}
  auxiliary_loss_weight: [0.4]
  ema_decay: 0.99
metric:
  task: segmentation
  compute_on_cpu: true
  sync_on_compute: false
  num_classes: 4
  include_background: true
  per_class: false
  input_format: one-hot
  target_metrics: [MeanIoU]
test: {target_metric: MeanIoU}
ddp: {world_size: 1, rank: -1, gpu: 0, dist_url: "env://", dist_backend: nccl, distributed: false, sync_bn: false}
